const wordBank = [
  { german: "Hallo", meaning: "hello" },
  { german: "Tschüss", meaning: "goodbye" },
  { german: "Bitte", meaning: "please" },
  { german: "Danke", meaning: "thank you" },
  { german: "Ja", meaning: "yes" },
  { german: "Nein", meaning: "no" },
  { german: "Buch", meaning: "book" },
  { german: "Schule", meaning: "school" },
  { german: "Haus", meaning: "house" },
  { german: "Katze", meaning: "cat" },
  { german: "Hund", meaning: "dog" },
  { german: "Wasser", meaning: "water" },
  { german: "Mutter", meaning: "mother" },
  { german: "Vater", meaning: "father" },
  { german: "Kind", meaning: "child" },
  { german: "Stadt", meaning: "city" },
  { german: "Mann", meaning: "man" },
  { german: "Frau", meaning: "woman" },
  { german: "Auto", meaning: "car" },
  { german: "Essen", meaning: "food" },
  { german: "Freund", meaning: "friend" },
  { german: "Arbeit", meaning: "work" },
  { german: "Geld", meaning: "money" },
  { german: "Zeit", meaning: "time" },
  { german: "Tag", meaning: "day" },
  { german: "Nacht", meaning: "night" },
  { german: "Morgen", meaning: "morning" },
  { german: "Abend", meaning: "evening" },
  { german: "Essen", meaning: "to eat" },
  { german: "Trinken", meaning: "to drink" },
  { german: "Schlafen", meaning: "to sleep" },
  { german: "Gehen", meaning: "to go" },
  { german: "Kommen", meaning: "to come" },
  { german: "Sehen", meaning: "to see" },
  { german: "Sprechen", meaning: "to speak" },
  { german: "Lesen", meaning: "to read" },
  { german: "Schreiben", meaning: "to write" },
  { german: "Lernen", meaning: "to learn" },
  { german: "Kaufen", meaning: "to buy" },
  { german: "Rot", meaning: "red" },
  { german: "Blau", meaning: "blue" },
  { german: "Grün", meaning: "green" },
  { german: "Groß", meaning: "big" },
  { german: "Klein", meaning: "small" },
  { german: "Neu", meaning: "new" },
  { german: "Alt", meaning: "old" },
  { german: "Gut", meaning: "good" },
  { german: "Schlecht", meaning: "bad" },
  { german: "Schnell", meaning: "fast" },
  { german: "Langsam", meaning: "slow" },
];